version: '3'
services:
  postgresql:
    image: postgres:11.5-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: cronjob_as_a_service
    volumes:
     - ${PWD}/.data/db:/var/lib/postgresql/data
