-- Your SQL goes here

CREATE TABLE users (
    id SERIAL PRIMARY KEY NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE jobs (
    id SERIAL PRIMARY KEY NOT NULL,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE ,
    schedule VARCHAR NOT NULL,
    command VARCHAR NOT NULL,
    last_run INTEGER NOT NULL,
    next_run INTEGER NOT NULL
);

CREATE TABLE secrets (
    id SERIAL PRIMARY KEY NOT NULL,
    job_id INTEGER NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    key TEXT NOT NULL,
    value TEXT NOT NULL
);
